### ISSUE TITLE
How to support websocket path

### ISSUE THREAD

**Issue by jinlife** [imgk/caddy-trojan#12]
How to support websocket path like trojan-go? 
https://github.com/p4gefau1t/trojan-go
To support WebSocket over TLS and the Cloudflare CDN.

"websocket": {
    "enabled": true,
    "path": "/your-websocket-path",
    "hostname": "www.your-awesome-domain-name.com"
}

**Comment by imgk** [comment]
Try Caddy subroot module. It may works.
