### ISSUE TITLE
The program crashes automatically

### ISSUE THREAD

**Issue by eamlinux** [imgk/caddy-trojan#13]
error message：
caddy[10980]: panic: runtime error: slice bounds out of range [:62378] with capacity 16384
caddy[10980]: goroutine 5505 [running]:
caddy[10980]: github.com/imgk/caddy-trojan/trojan.HandleUDP.func1(0xc000512c68, {0x7fd2109d4718, 0xc00097f500}, 0xc000074ae0?)
caddy[10980]:         github.com/imgk/caddy-trojan@v0.0.0-20220313085740-c9d51ad2436b/trojan/trojan_udp.go:72 +0x545
caddy[10980]: created by github.com/imgk/caddy-trojan/trojan.HandleUDP
caddy[10980]:         github.com/imgk/caddy-trojan@v0.0.0-20220313085740-c9d51ad2436b/trojan/trojan_udp.go:30 +0x16b
systemd[1]: caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: caddy.service: Failed with result 'exit-code'.
systemd[1]: caddy.service: Consumed 32.130s CPU time.

**Comment by imgk** [comment]
Try dev branch.

**Comment by eamlinux** [comment]
> ‎尝试开发分支。‎

Thanks!
