### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by Gzxhwq** [imgk/caddy-trojan#14]
https://github.com/Gzxhwq/caddy-cloudflaredns/runs/5610293409?check_suite_focus=true

# github.com/imgk/caddy-trojan/memory
/go/pkg/mod/github.com/imgk/caddy-trojan@v0.0.0-20220319045627-0efea8838f79/memory/alloc.go:4:14: syntax error: unexpected any, expecting ]
/go/pkg/mod/github.com/imgk/caddy-trojan@v0.0.0-20220319045627-0efea8838f79/memory/alloc.go:9:17: syntax error: unexpected [, expecting comma or )
/go/pkg/mod/github.com/imgk/caddy-trojan@v0.0.0-20220319045627-0efea8838f79/memory/alloc.go:14:17: syntax error: unexpected [, expecting comma or )
/go/pkg/mod/github.com/imgk/caddy-trojan@v0.0.0-20220319045627-0efea8838f79/memory/alloc_go.go:7:6: missing function body
/go/pkg/mod/github.com/imgk/caddy-trojan@v0.0.0-20220319045627-0efea8838f79/memory/alloc_go.go:7:11: syntax error: unexpected [, expecting (
/go/pkg/mod/github.com/imgk/caddy-trojan@v0.0.0-20220319045627-0efea8838f79/memory/alloc_go.go:12:6: missing function body
/go/pkg/mod/github.com/imgk/caddy-trojan@v0.0.0-20220319045627-0efea8838f79/memory/alloc_go.go:12:10: syntax error: unexpected [, expecting (

**Comment by imgk** [comment]
Use go 1.18

**Comment by Gzxhwq** [comment]
OK. Let's wait for official docker builder update with Go 1.18
