### ISSUE TITLE
Caddyfile not works

### ISSUE THREAD

**Issue by xh116** [imgk/caddy-trojan#15]
Hi 
It seems the latest commit has conflict with Caddyfile. (tested json config file works.)

`run: loading initial config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 1: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: module name not specified with key 'handler' in map[]`

**Comment by imgk** [comment]
Fixed.
