### ISSUE TITLE
Build FATAL

### ISSUE THREAD

**Issue by eamlinux** [imgk/caddy-trojan#17]
go version go1.18 linux/amd64

FATAL:
2022/03/29 14:42:44 [INFO] Build environment ready
2022/03/29 14:42:44 [INFO] Building Caddy
2022/03/29 14:42:44 [INFO] exec (timeout=0s): /usr/local/bin/go mod tidy
caddy imports
        github.com/caddyserver/caddy/v2/modules/standard imports
        github.com/caddyserver/caddy/v2/modules/caddypki imports
        github.com/smallstep/certificates/authority imports
        github.com/smallstep/certificates/kms tested by
        github.com/smallstep/certificates/kms.test imports
        github.com/smallstep/certificates/kms/cloudkms imports
        cloud.google.com/go/kms/apiv1: ambiguous import: found package cloud.google.com/go/kms/apiv1 in multiple modules:
        cloud.google.com/go v0.83.0 (/home/wiselau/go/pkg/mod/cloud.google.com/go@v0.83.0/kms/apiv1)
        cloud.google.com/go/kms v1.1.0 (/home/wiselau/go/pkg/mod/cloud.google.com/go/kms@v1.1.0/apiv1)
2022/03/29 14:42:44 [INFO] Cleaning up temporary folder: /tmp/buildenv_2022-03-29-1442.3882018425
2022/03/29 14:42:44 [FATAL] exit status 1

**Comment by xh116** [comment]
https://github.com/caddyserver/caddy/pull/4665 
And tested, if you add  this module `  --with github.com/caddyserver/transform-encoder ` also, the error will disappear.

**Comment by imgk** [comment]
`xcaddy build master --with github.com/imgk/caddy-trojan`
