### ISSUE TITLE
compatibility with forwardproxy module 

### ISSUE THREAD

**Issue by xh116** [imgk/caddy-trojan#2]
firstly, Thanks for this project !

I often use naiveproxy which is based on another module of Caddy called forwardyproxy (https://github.com/caddyserver/forwardproxy). however it is not compatible with most of mobile clients.  
After testing your project, I found it very efficient to solve this problem.

but seems the two modules are not compatible. 

```
 :443, xx.yy.com {
tls xx@yy.com
trojan_gfw
route {
 forward_proxy {
    basic_auth user password
    hide_ip
    hide_via
    probe_resistance 
  }
  trojan // for websocket
  file_server { root /var/www/html }
 }
}
```

do you have any suggestions

**Comment by imgk** [comment]
How about put trojan before forward_proxy?

```
:443, xx.yy.com {
tls xx@yy.com
trojan_gfw
route {
 trojan
 forward_proxy {
    basic_auth user password
    hide_ip
    hide_via
    probe_resistance 
  }
  file_server { root /var/www/html }
 }
}
```

**Comment by xh116** [comment]
Tried, but not work. 
Although the caddy and trojan are running but forwardproxy and web server seems have problems:  `ERR_HTTP2_PROTOCOL_ERROR` when opening in chrome

**Comment by xh116** [comment]
Thanks.
but I found a tricky 
I can make only one work by changing the servers port :  

**forwardproxy works**
```
{
    http_port 80
    https_port 443
    servers  localhost    {
        protocol {
            allow_h2c
     }
    }
}

```

**trojan works** 
```

{
    http_port 80
    https_port 443
    servers      localhost:2019 {
        protocol {
            allow_h2c
     }
    }
}

```

any suggestion to make both of them work ?

**Comment by 82kg** [comment]
画画的贝贝 画画的贝贝

**Comment by xh116** [comment]
@imgk 
Finally solved for both json and caddyfile.  
Just simply adding 
```
      listener_wrappers {
      trojan
    }
```
under server

**Comment by xh116** [comment]
By the way, when caddy restarted, the trojan user will disappear.
If it is hard to implement in caddy config, is that possible to read a json file from outside?

**Comment by imgk** [comment]
> By the way, when caddy restarted, the trojan user will disappear.
> If it is hard to implement in caddy config, is that possible to read a json file from outside?

I delete the feature of adding users from config file. Normally, you will set trojan in two different places in a config file, `listener_wrapper` and `handler`. It is confusing when adding users. Where to put user password? Do they work for these two “trojan”?

This module is stable and can work for long time. There is no need to restart caddy. If you use `caddy reload`, trojan users will not disappear.

We may can add a feature about persisting trojan users.
