### ISSUE TITLE
无法编译了

### ISSUE THREAD

**Issue by lxhao61** [imgk/caddy-trojan#20]
![image](https://user-images.githubusercontent.com/24571146/162290510-8d0c233d-cf5e-422c-b564-ebc7097f8700.png)

**Comment by imgk** [comment]
See #17.

**Comment by lxhao61** [comment]
编译其它插件正常。go version go1.17.8。

**Comment by lxhao61** [comment]
> See #17.

编译其它插件正常。go version go1.17.8。

**Comment by imgk** [comment]
See #14.

**Comment by lxhao61** [comment]
> See #14.

go升级到go1.18，非docker builder环境编译，问题依旧。

**Comment by imgk** [comment]
这个是 go module 的问题，模块本身没问题。

This is an issue with the go module. This caddy module is fine.

**Comment by lxhao61** [comment]
> 这个是 go module 的问题，模块本身没问题。
> 
> This is an issue with the go module. This caddy module is fine.

但其它插件在非go1.18下（如1.17.8）编译都正常，只有caddy-trojan不正常；不是仅 go module 的问题，模块本身没问题吧？

**Comment by imgk** [comment]
> > 这个是 go module 的问题，模块本身没问题。
> > This is an issue with the go module. This caddy module is fine.
> 
> 但其它插件在非go1.18下（如1.17.8）编译都正常，只有caddy-trojan不正常；无论怎么看都不是仅 go module 的问题，模块本身没问题吧？

因为这个模块用了只有 go 1.18 支持的功能，比如泛型

**Comment by lxhao61** [comment]
> > > 这个是 go module 的问题，模块本身没问题。
> > > This is an issue with the go module. This caddy module is fine.
> > 
> > 
> > 但其它插件在非go1.18下（如1.17.8）编译都正常，只有caddy-trojan不正常；无论怎么看都不是仅 go module 的问题，模块本身没问题吧？
> 
> 因为这个模块用了只有 go 1.18 支持的功能，比如泛型

好吧，明白了。但非go1.18不支持，go 1.18（go module 问题）不能正常编译，只能等待了。
