### ISSUE TITLE
支持上级代理和 TCP 代码优化

### ISSUE THREAD

**Issue by wen-long** [imgk/caddy-trojan#22]
首先感谢作者提供了很好的思路，嵌入到 caddy 中是十分优雅的实现

看了下代码，提两个建议
1. tcp 发起连接使用 x/net/proxy，可以自动处理环境变量中的 HTTP_PROXY，十分好用
2. tcp 交换数据的代码是不是有些复杂，本质是两个 io.Copy，可以考虑下

我自己实现了下，代码如下，暂时自用以发现问题

https://github.com/wen-long/caddy-trojan/commit/17a2feb9ec061b72d0a246d1820172fa509f24c2

编译:
`xcaddy build master --with github.com/wen-long/caddy-trojan@17a2feb9ec061b72d0a246d1820172fa509f24c2`

**Comment by imgk** [comment]
1、支持上级代理是个想法，这个需求大吗？
2、TCP 数据交换这么麻烦，主要原因是使用 HTTP2/3 连接时如果不这么写，连接不能正常关闭

**Comment by wen-long** [comment]
> 1、支持上级代理是个想法，这个需求大吗？ 2、TCP 数据交换这么麻烦，主要原因是使用 HTTP2 连接时如果不这么写，部分连接不能正常关闭

1 是网络环境友好，go 是静态的，LD_PRELOAD 这样的机制不能用，有时候想让 go 走代理，指定了 HTTP_PROXY 但有没有效要看程序是不是友好。不过看你新的提交已经做了
2 我改的部分已经跑了一阵子了，没有发现问题。不过没试过 http2。这块我不太明白，是用官方 C++ 客户端配置 h2 来使用吗？但我测试看到指定了 ssl.alpn.h2 收到的数据仍然是原生协议。

另外。http.handlers.trojan 这块好像跟原协议无关？Proxy-Authorization 的格式浏览器也没法支持，这块是做什么的呢？

**Comment by imgk** [comment]
1、支持`HTTP_PROXY`没什么问题；
2、目前没有什么官方的`over HTTP2`的标准吧，那个是我自己定义的。
