### ISSUE TITLE
一处协议探测弱点

### ISSUE THREAD

**Issue by wen-long** [imgk/caddy-trojan#23]
https://github.com/imgk/caddy-trojan/blob/01836ae4d1e56eb96e60b8c6fafc937ad6041dc6/listener/listener.go#L159

这里检查协议的第一次 0D0A. HTTP 协议虽然规定以 0D0A 分割，但 nginx 和基本全部在线的 web 服务器都是按 nginx 的头部解析过程来实现的。参考代码
https://github.com/nginx/nginx/blob/master/src/http/ngx_http_parse.c#L1049

nginx 中， 0D(\r) 是可以重复或略过，其后必须有一个 0A(\n)
举例：
向正常的 http 服务器
发送 `whatever\r\r\r\r\r\r\` 服务器会等待 
发送 `whatever\n\n\n\n\n` 服务器返回错误页面

而本项目发送 `whatever\n\n\n\n\n` 服务器会继续等待，表现与正常 web 服务器不同
因此这里不必要求 \n 前有 \r

```
if n > 1 && b[n] == 0x0a && n < trojan.HeaderLen+1 
```

**Comment by wen-long** [comment]
使用 stunnel + https://packetsender.com/ 很容易复现

**Comment by imgk** [comment]
你可以提一个PR不？

**Comment by wen-long** [comment]
> 你可以提一个PR不？

要动手的话，是不是先了解下你的目的，storage 存用户信息这块我不知道是何用意，是否是在 redis 中保存鉴权和汇总流量？
用户检查跟这块有关

trojan 原生协议避免探测重要的就是头部的检查，要像 http 服务器一样对头部尽早的，尽少数据的去判断是不是合法 trojan 数据。所以最优雅，也最正确的姿势是每收到一点数据，立马判断是否有“合法”的可能。一旦没有合法的可能，就交给 http 了。而合法的检查只需在前 56 字节完成，56 字节完成后，后续的操作就不需要太严格了。
所以实现起来就是尽快处理接收到的任意一点数据，马上匹配所有合法用户 ID，判断有无继续等待的必要。这里要频繁调用用户信息模块，如果用户很多，可能得需要特别优化

我自己写了点，目前运行良好，像下图一样收到 `\n\n` 立马返回 html 是符合一般 web 服务器行为的。

https://github.com/wen-long/caddy-trojan/commit/e05090bce31b2ed784f37b29fc5b0943c66778a9

![image](https://user-images.githubusercontent.com/4262398/163426841-f7a0d90d-709f-49cb-82dd-b36d996603f9.png)

**Comment by imgk** [comment]
https://github.com/imgk/caddy-trojan/blob/3b0f0cc2e81cfccb8825bbfb4b38286ca38a56e3/listener/listener.go#L149-L173

**Comment by wen-long** [comment]
上面我提到 nginx 的解析实现应作为参考。现在看有点骑马找驴
go 本身就有 http sever 的代码实现，caddy 跑起来也可能在 TLS 层体现了 go web server 的特性
所以假装自己是 nginx 是没有必要的，只需要假装自己是普通的 caddy web server

我参考
https://github.com/golang/go/blob/19309779ac5e2f5a2fd3cbb34421dafb2855ac21/src/net/http/request.go#L1037
自己改了个，提交在 
https://github.com/wen-long/caddy-trojan/commit/ec2b7eb55b12d250b2ba4dacfa31a3287ef74b24

https://go.dev 就是一个 go web server,通过包探测可以确定首行的解析行为是一致的
