### ISSUE TITLE
trojan+http2无法连接

### ISSUE THREAD

**Issue by rockyzhng** [imgk/caddy-trojan#25]
"allow_h2c": true,
                    "routes": [
                        {
                            "handle": [
                                {
                                    "handler": "trojan",
                                    "connect_method": false,
                                    "websocket": false
                                }
                            ]
                        }
                    ]
当服务器上的caddy配置文件中"allow_h2c": 值为:true时，客户端上选择trojan+http2(host和path都留空)时无法连接，只有trojan+tcp才可以连接，设置这个参数的意义何在？需要填什么吗？

**Comment by imgk** [comment]
你是用什么客户端？目前trojan+tcp是没问题，http2这个是我自定义的方式，应该没有客户锻支持

**Comment by rockyzhng** [comment]
测试客户端为android上的v2rayng。
我以前用caddy+v2ray搭建的，经测试trojan+tcp，trojan+websocket，trojan+http2，trojan+grpc，这四种方式都可以连接。
http2和grpc支持多路复用，对速度的改善还是很大的。
grpc相比http2只有少许提升，主要是可以套cdn，虽然caddy原生只支持http2，grpc需要额外插件才支持，但我还是希望您这个项目可以支持trojan+http2或者trojan+grpc。

**Comment by imgk** [comment]
我个人没这个需求，也没有时间去做，欢迎其他人提 PR

**Comment by rockyzhng** [comment]
哈哈，刚才在关闭的pr当中，我看见已经有人提过trojan+grpc了。
我以为trojan+http2是可用的，就没去看pr了。
