### ISSUE TITLE
能否支持trojan-go的mux模式？

### ISSUE THREAD

**Issue by bash99** [imgk/caddy-trojan#27]
对降低延迟有较好作用，而且从隐藏流量特征的角度也更好一点。（毕竟现在的h2协议下并发连接数明显变少）

**Comment by imgk** [comment]
支持 Trojan over HTTP2 和 Trojan over HTTP3 是可以的，困难是现在有没有个统一的标准， 不知道 v2ray 和 trojan-go 的实现有没有区别，如果一个软件一个实现，就不太想支持，欢迎提供更多信息

**Comment by bash99** [comment]
> 支持 Trojan over HTTP2 和 Trojan over HTTP3 是可以的，困难是现在有没有个统一的标准， 不知道 v2ray 和 trojan-go 的实现有没有区别，如果一个软件一个实现，就不太想支持，欢迎提供更多信息

trojan-go的mux实现和v2ray不一样，是smux，v2ray的mux一直没有特别稳定过。不过暂时客户端除了trojan-go自己的支持不多。
