### ISSUE TITLE
建议配置参数简约化

### ISSUE THREAD

**Issue by lxhao61** [imgk/caddy-trojan#30]
大佬，现在配置参数是否可以回到以前，甚至比以前更加简约化。
觉得现在配置参数太繁琐（多个配置块、多个关联参数无条理。），希望一个配置块搞定（类似naiveproxy配置）。

**Comment by imgk** [comment]
这个是`caddy`配置文件的问题，如果只支持 trojan over tls 是可以简化配置文件的，现在是有机会支持 gRPC 等其他连接方式，就比较麻烦
