### ISSUE TITLE
Missing description and explanation

### ISSUE THREAD

**Issue by Minecodes** [imgk/caddy-trojan#32]
I looked at this project for quite a while and was wandering for what it is. Because usually the plugins have description what they do and about what they are for. Can you please add that? Because I'm a beginner in Go and I'm not understanding what the plugin does in the code.

**Comment by ArcCal** [comment]
如果你真感兴趣，肯定了解这是什么。你不了解，为什么会感兴趣？

**Comment by Minecodes** [comment]
> 如果你真感兴趣，肯定了解这是什么。你不了解，为什么会感兴趣？

Sorry, I had to use Google Translate.

我不知道这个存储库到底做了什么，这就是我问的原因。 到目前为止，我唯一能读到的只有一个 websocket 处理程序，在那里我只了解 read、close 和新的连接方法，但不了解 write 函数。 然后我能够找到一个我不理解的代理，因为我没有调查过它。 否则我只能找到一个用户管理系统。 这可能是为了保护底层 API。 但我不明白其余的上下文。

**Comment by Waitung** [comment]
这是一个用于实现trojan代理服务端的插件，trojan协议参考：
https://github.com/trojan-gfw/trojan
https://github.com/p4gefau1t/trojan-go

**Comment by Minecodes** [comment]
> 这是一个用于实现trojan代理服务端的插件，trojan协议参考：
> https://github.com/trojan-gfw/trojan
> https://github.com/p4gefau1t/trojan-go

感谢您的及时答复。
