### ISSUE TITLE
请问为什么必须在配置中需要启用h2c协议？

### ISSUE THREAD

**Issue by IriKaQ** [imgk/caddy-trojan#38]
Caddy官方文档中不建议启用h2c，请问trojan是必须要启用h2c才能使用吗？

**Comment by IriKaQ** [comment]
我尝试移除了`protocols h1 h2c h2`这一行配置，也可以正常访问。

**Comment by imgk** [comment]
之前是不开启是没办法使用http2的，现在好像没问题了
