### ISSUE TITLE
想了解一下这个插件的trojan是使用什么加密方式连接的

### ISSUE THREAD

**Issue by pmkol** [imgk/caddy-trojan#43]
如题，因为经过我近20台服务器的测试，对客户端连接加密方式的控制，可以有效预防封端口问题产生，但考虑到客户端众多，所以原来用nginx+trojan的方案，强制在服务端指定了加密算法。

这个插件的trojan该如何控制？caddy的protocols与ciphers，对这个trojan插件的连接算法指定也生效么？

**Comment by imgk** [comment]
这个只是 caddy 的一个插件，相关配置都参考 caddy 的设置，protocols 与 ciphers 直接在 caddy 中设置即可

PS: 我没这个需求，所以没有实际测试过

**Comment by ArcCal** [comment]
> 如题，因为经过我近20台服务器的测试，对客户端连接加密方式的控制，可以有效预防封端口问题产生，但考虑到客户端众多，所以原来用nginx+trojan的方案，强制在服务端指定了加密算法。
> 
> 这个插件的trojan该如何控制？caddy的protocols与ciphers，对这个trojan插件的连接算法指定也生效么？

能分享下“对客户端连接加密方式的控制，可以有效预防封端口问题产生”有关的经验不
