### ISSUE TITLE
密码存放的位置

### ISSUE THREAD

**Issue by pmkol** [imgk/caddy-trojan#45]
如题
curl -X POST -H "Content-Type: application/json" -d '{"password": "test1234"}' http://localhost:2019/trojan/users/add
这个方法添加的密码，存储在哪，如果我想删除密码，应该怎么做？

**Comment by imgk** [comment]
这个取决于你的 caddy 配置文件中 `storage` 如何配置的，目前是存在这个目录中 `trojan` 子目录下面
