### ISSUE TITLE
本插件使用当前Caddy master源码编译报错

### ISSUE THREAD

**Issue by lxhao61** [imgk/caddy-trojan#54]
xcaddy build master --with github.com/imgk/caddy-trojan
![image](https://user-images.githubusercontent.com/24571146/229845530-852f6178-d1bc-4844-8269-4efb5bed8f40.png)

**Comment by imgk** [comment]
最新版Caddy有些修改，因为没正式发布，我也没改了，不用master版就好了

**Comment by lxhao61** [comment]
> 最新版Caddy有些修改，因为没正式发布，我也没改了，不用master版就好了

是的，但现在master版改动很多（新功能：如自带caddy2-proxyprotocol与等效realip的插件等。），若此插件不对应修改，那么想同时使用就无法了。

**Comment by imgk** [comment]
`xcaddy build --with github.com/imgk/caddy-trojan@master`
