### ISSUE TITLE
打印了大量的log

### ISSUE THREAD

**Issue by IriKaQ** [imgk/caddy-trojan#56]
> web_1             | {"level":"error","ts":1685293954.0146098,"logger":"caddy.listeners.trojan","msg":"read prefix error: read tcp <client ip>:18629 -> 172.18.0.15:443: read: EOF"}
> web_1             | {"level":"error","ts":1685294244.9202943,"logger":"caddy.listeners.trojan","msg":"read prefix error, not io, rewind and let normal caddy deal with it: no certificate available for '172.18.0.15'"}
> web_1             | {"level":"error","ts":1685294244.930999,"logger":"caddy.listeners.trojan","msg":"read prefix error, not io, rewind and let normal caddy deal with it: no certificate available for '172.18.0.15'"}
> web_1             | {"level":"error","ts":1685294244.9397044,"logger":"caddy.listeners.trojan","msg":"read prefix error, not io, rewind and let normal caddy deal with it: no certificate available for '172.18.0.15'"}
> web_1             | {"level":"error","ts":1685294244.9489136,"logger":"caddy.listeners.trojan","msg":"read prefix error, not io, rewind and let normal caddy deal with it: no certificate available for '172.18.0.15'"}
> web_1             | {"level":"error","ts":1685294244.9561362,"logger":"caddy.listeners.trojan","msg":"read prefix error, not io, rewind and let normal caddy deal with it: no certificate available for '172.18.0.15'"}
> web_1             | {"level":"error","ts":1685294244.9757292,"logger":"caddy.listeners.trojan","msg":"read prefix error, not io, rewind and let normal caddy deal with it: no certificate available for '172.18.0.15'"}
> web_1             | {"level":"error","ts":1685294318.235925,"logger":"caddy.listeners.trojan","msg":"read prefix error, not io, rewind and let normal caddy deal with it: no certificate available for 'hkbgp.fccloud.xyz'"}
> web_1             | {"level":"error","ts":1685294355.2818253,"logger":"caddy.listeners.trojan","msg":"read prefix error: read tcp <client ip>:19079 -> 172.18.0.15:443: read: EOF"}

上述 log 中有两种类型的报错 log：1. 是 _read: EOF"_，2. 是 _no certificate available for_。

请问，这两种 log 为什么是 trojan 来打印呢？特别是第二种，不应该是 caddy 本身来负责吗？

**Comment by imgk** [comment]
不是的，连接到服务器上的 TCP 链接，caddy 先包一层 TLS，就交给 trojan 读取了。

第一种链接来了却没发送足量的数据就关闭了，所以出现EOF错误。

第二种应该是在读取发生时再进行握手，所以错误由 trojan 处理

https://github.com/imgk/caddy-trojan/blob/2631719e16c887a8b4e285431e4a24a5fb8036d5/listener/listener.go#L153

**Comment by IriKaQ** [comment]
这个 trojan 插件不是工作在 caddy tls terminate  之后吗？

**Comment by imgk** [comment]
可能只是包装了一下，并没有真正进行握手，转到`trojan`读取时再握手，也是`trojan`处理错误
