### ISSUE TITLE
编译最新的caddy 2.7.0-beta.2.0（0e2c7e1）报错

### ISSUE THREAD

**Issue by text01001** [imgk/caddy-trojan#58]
caddy commit：
https://github.com/caddyserver/caddy/commit/0e2c7e1d35b287fc0e56d6db2951f791e09b5a37
加master分支的trojan：
--with github.com/imgk/caddy-trojan@master

报错：
# github.com/imgk/caddy-trojan/admin
/root/gopath/pkg/mod/github.com/imgk/caddy-trojan@v0.0.0-20230413030132-1eea7af93ca2/admin/admin.go:34:15: assignment mismatch: 2 variables but ctx.AppIfConfigured returns 1 value
# github.com/imgk/caddy-trojan/handler
/root/gopath/pkg/mod/github.com/imgk/caddy-trojan@v0.0.0-20230413030132-1eea7af93ca2/handler/handler.go:58:15: assignment mismatch: 2 variables but ctx.AppIfConfigured returns 1 value
# github.com/imgk/caddy-trojan/listener
/root/gopath/pkg/mod/github.com/imgk/caddy-trojan@v0.0.0-20230413030132-1eea7af93ca2/listener/listener.go:50:15: assignment mismatch: 2 variables but ctx.AppIfConfigured returns 1 value

**Comment by imgk** [comment]
Fixed
