### ISSUE TITLE
Caddy 版本依赖建议

### ISSUE THREAD

**Issue by mritd** [imgk/caddy-trojan#60]
## 问题描述

目前有一个自动化任务在定时编译 Caddy, 其中为了保持插件更新会定期 rebuild; 现在遇到的问题是 **trojan 插件使用了未发布的 Caddy 版本, 导致在编译 release 版本时出现依赖错误**

## 解决建议

能否新开一个分支用于对下一个版本的开发, main 分支保持与当前 Caddy release 锁定, 如果 hotfix 之类的可以直接 main 分支 commit; 这样可以保证 main 一直可以兼容最新的 Caddy release.

**Comment by lxhao61** [comment]
支持！
