### ISSUE TITLE
failed to build with v2.8.0-rc.1

### ISSUE THREAD

**Issue by cattyhouse** [imgk/caddy-trojan#65]
failed to build with v2.8.0-rc.1, but v2.8.0-beta.2 is ok.
```
# github.com/imgk/caddy-trojan/admin
../admin/admin.go:35:5: multiple-value ctx.AppIfConfigured(app.CaddyAppID) (value of type (any, error)) in single-value context
# github.com/imgk/caddy-trojan/listener
../listener/listener.go:51:5: multiple-value ctx.AppIfConfigured(app.CaddyAppID) (value of type (any, error)) in single-value context
# github.com/imgk/caddy-trojan/handler
../handler/handler.go:61:5: multiple-value ctx.AppIfConfigured(app.CaddyAppID) (value of type (any, error)) in single-value context
```

**Comment by lxhao61** [comment]
> this fixed the build :)
> 
> ```diff
> -   if ctx.AppIfConfigured(app.CaddyAppID) == nil {
> +    _, err := ctx.AppIfConfigured(app.CaddyAppID)
> +   if err == nil {
> ```
> 
> but failed to run:
> 
> ```
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xada772]
> goroutine 1 [running]:
> github.com/caddyserver/caddy/v2.Context.AppIfConfigured({{0x0, 0x0}, 0x0, 0x0, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...)
>         /Users/m1/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.8.0-rc.1/context.go:462 +0x32
> github.com/caddyserver/caddy/v2/modules/caddytls.(*TLS).Cleanup(0xc00047dc20)
>         /Users/m1/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.8.0-rc.1/modules/caddytls/tls.go:356 +0xc5
> github.com/caddyserver/caddy/v2.NewContext.func1()
>         /Users/m1/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.8.0-rc.1/context.go:73 +0x162
> github.com/caddyserver/caddy/v2.run.func1()
>         /Users/m1/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.8.0-rc.1/caddy.go:427 +0x1d
> github.com/caddyserver/caddy/v2.run(0x2000107?, 0x1)
>         /Users/m1/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.8.0-rc.1/caddy.go:495 +0x918
> github.com/caddyserver/caddy/v2.unsyncedDecodeAndRun({0xc0006fcc00, 0x3fc, 0x400}, 0x1)
>         /Users/m1/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.8.0-rc.1/caddy.go:343 +0x145
> github.com/caddyserver/caddy/v2.changeConfig({0x1a78346, 0x4}, {0x1a7f2bc, 0x7}, {0xc0006fc800, 0x3fc, 0x400}, {0x0, 0x0}, 0x1)
>         /Users/m1/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.8.0-rc.1/caddy.go:234 +0x6b6
> github.com/caddyserver/caddy/v2.Load({0xc0006fc800, 0x3fc, 0x400}, 0x1)
>         /Users/m1/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.8.0-rc.1/caddy.go:133 +0x236
> github.com/caddyserver/caddy/v2/cmd.cmdRun({0x0?})
>         /Users/m1/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.8.0-rc.1/cmd/commandfuncs.go:231 +0x831
> github.com/caddyserver/caddy/v2/cmd.init.1.func2.WrapCommandFuncForCobra.1(0xc000650608, {0x1a783a2?, 0x4?, 0x1a78376?})
>         /Users/m1/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.8.0-rc.1/cmd/cobra.go:137 +0x2f
> github.com/spf13/cobra.(*Command).execute(0xc000650608, {0xc0006b4b70, 0x3, 0x3})
>         /Users/m1/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
> github.com/spf13/cobra.(*Command).ExecuteC(0x2ccd980)
>         /Users/m1/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
> github.com/spf13/cobra.(*Command).Execute(...)
>         /Users/m1/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
> github.com/caddyserver/caddy/v2/cmd.Main()
>         /Users/m1/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.8.0-rc.1/cmd/main.go:75 +0x1d8
> main.main()
>         /Users/m1/make/caddy-trojan/buildenv_2024-05-22-1107.4089470155/main.go:12 +0xf
> ```

What about the repaired source code link of caddy-trojan?

**Comment by lxhao61** [comment]
> @lxhao61 what do you mean? i am not sure i understand.

Didn't you fix caddy-trojan and then compile Caddy?

**Comment by lxhao61** [comment]
Sorry, I didn't look carefully. I thought it was compiled successfully after your modification, so I need to fix the caddy-trojan link.

**Comment by imgk** [comment]
Please try 4ce03fdd0a1756b4ebf8550ab4cd5571c0943a8c

**Comment by lxhao61** [comment]
> Please try [4ce03fd](https://github.com/imgk/caddy-trojan/commit/4ce03fdd0a1756b4ebf8550ab4cd5571c0943a8c)

编译不出错了，但编译好的文件不能启动，报错如下：
May 22 15:55:00 C20240207094726 systemd[1]: Starting Caddy...
May 22 15:55:01 C20240207094726 caddy[737]: {"level":"warn","ts":1716393301.1105406,"msg":"unable to determine directory for user configuration; falling back to current directory","error":"neither $XDG_CONFIG_HOME nor $HOME are defined"}
May 22 15:55:01 C20240207094726 caddy[737]: caddy.HomeDir=.
May 22 15:55:01 C20240207094726 caddy[737]: caddy.AppDataDir=./caddy
May 22 15:55:01 C20240207094726 caddy[737]: {"level":"warn","ts":1716393301.11432,"msg":"unable to determine directory for user configuration; falling back to current directory","error":"neither $XDG_CONFIG_HOME nor $HOME are defined"}
May 22 15:55:01 C20240207094726 caddy[737]: caddy.AppConfigDir=./caddy
May 22 15:55:01 C20240207094726 caddy[737]: caddy.ConfigAutosavePath=caddy/autosave.json
May 22 15:55:01 C20240207094726 caddy[737]: caddy.Version=v2.8.0-rc.1.0.20240521224141-61917c344342 h1:4Jo1tuqSTa+byPCbtnslUAlfaqOeneU8rAwqF0R25Vo=
May 22 15:55:01 C20240207094726 caddy[737]: runtime.GOOS=linux
May 22 15:55:01 C20240207094726 caddy[737]: runtime.GOARCH=amd64
May 22 15:55:01 C20240207094726 caddy[737]: runtime.Compiler=gc
May 22 15:55:01 C20240207094726 caddy[737]: runtime.NumCPU=2
May 22 15:55:01 C20240207094726 caddy[737]: runtime.GOMAXPROCS=2
May 22 15:55:01 C20240207094726 caddy[737]: runtime.Version=go1.22.3
May 22 15:55:01 C20240207094726 caddy[737]: os.Getwd=/
May 22 15:55:01 C20240207094726 caddy[737]: LANG=C.UTF-8
May 22 15:55:01 C20240207094726 caddy[737]: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
May 22 15:55:01 C20240207094726 caddy[737]: NOTIFY_SOCKET=/run/systemd/notify
May 22 15:55:01 C20240207094726 caddy[737]: LOGNAME=nobody
May 22 15:55:01 C20240207094726 caddy[737]: USER=nobody
May 22 15:55:01 C20240207094726 caddy[737]: INVOCATION_ID=dfeba5b2a39e4228a561c420baa00c5b
May 22 15:55:01 C20240207094726 caddy[737]: JOURNAL_STREAM=8:37180
May 22 15:55:01 C20240207094726 caddy[737]: {"level":"info","ts":1716393301.1145625,"msg":"using config from file","file":"/usr/local/etc/caddy/caddy.json"}
May 22 15:55:01 C20240207094726 caddy[737]: {"level":"info","ts":1716393301.1181679,"msg":"redirected default logger","from":"stderr","to":"/var/log/caddy/default.log"}
May 22 15:55:01 C20240207094726 systemd[1]: Started Caddy.
May 22 15:55:01 C20240207094726 caddy[737]: panic: runtime error: invalid memory address or nil pointer dereference
May 22 15:55:01 C20240207094726 caddy[737]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xadadd2]
May 22 15:55:01 C20240207094726 caddy[737]: goroutine 1 [running]:
May 22 15:55:01 C20240207094726 caddy[737]: github.com/caddyserver/caddy/v2.Context.AppIfConfigured({{0x0, 0x0}, 0x0, 0x0, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...)
May 22 15:55:01 C20240207094726 caddy[737]:         github.com/caddyserver/caddy/v2@v2.8.0-rc.1.0.20240521224141-61917c344342/context.go:462 +0x32
May 22 15:55:01 C20240207094726 caddy[737]: github.com/caddyserver/caddy/v2/modules/caddytls.(*TLS).Cleanup(0xc0004d1b30)
May 22 15:55:01 C20240207094726 caddy[737]:         github.com/caddyserver/caddy/v2@v2.8.0-rc.1.0.20240521224141-61917c344342/modules/caddytls/tls.go:356 +0xc5
May 22 15:55:01 C20240207094726 caddy[737]: github.com/caddyserver/caddy/v2.NewContext.func1()
May 22 15:55:01 C20240207094726 caddy[737]:         github.com/caddyserver/caddy/v2@v2.8.0-rc.1.0.20240521224141-61917c344342/context.go:73 +0x162
May 22 15:55:01 C20240207094726 caddy[737]: github.com/caddyserver/caddy/v2.run.func1()
May 22 15:55:01 C20240207094726 caddy[737]:         github.com/caddyserver/caddy/v2@v2.8.0-rc.1.0.20240521224141-61917c344342/caddy.go:427 +0x1d
May 22 15:55:01 C20240207094726 caddy[737]: github.com/caddyserver/caddy/v2.run(0x8000102?, 0x1)
May 22 15:55:01 C20240207094726 caddy[737]:         github.com/caddyserver/caddy/v2@v2.8.0-rc.1.0.20240521224141-61917c344342/caddy.go:495 +0x918
May 22 15:55:01 C20240207094726 caddy[737]: github.com/caddyserver/caddy/v2.unsyncedDecodeAndRun({0xc0005b4000, 0xe7b, 0x1000}, 0x1)
May 22 15:55:01 C20240207094726 caddy[737]:         github.com/caddyserver/caddy/v2@v2.8.0-rc.1.0.20240521224141-61917c344342/caddy.go:343 +0x145
May 22 15:55:01 C20240207094726 caddy[737]: github.com/caddyserver/caddy/v2.changeConfig({0x1a28b36, 0x4}, {0x1a2fc05, 0x7}, {0xc00057c000, 0x1d12, 0x1d13}, {0x0, 0x0}, 0x1)
May 22 15:55:01 C20240207094726 caddy[737]:         github.com/caddyserver/caddy/v2@v2.8.0-rc.1.0.20240521224141-61917c344342/caddy.go:234 +0x6b6
May 22 15:55:01 C20240207094726 caddy[737]: github.com/caddyserver/caddy/v2.Load({0xc00057c000, 0x1d12, 0x1d13}, 0x1)
May 22 15:55:01 C20240207094726 caddy[737]:         github.com/caddyserver/caddy/v2@v2.8.0-rc.1.0.20240521224141-61917c344342/caddy.go:133 +0x236
May 22 15:55:01 C20240207094726 caddy[737]: github.com/caddyserver/caddy/v2/cmd.cmdRun({0x0?})
May 22 15:55:01 C20240207094726 caddy[737]:         github.com/caddyserver/caddy/v2@v2.8.0-rc.1.0.20240521224141-61917c344342/cmd/commandfuncs.go:231 +0x831
May 22 15:55:01 C20240207094726 caddy[737]: github.com/caddyserver/caddy/v2/cmd.init.1.func2.WrapCommandFuncForCobra.1(0xc00001c608, {0x1a28bba?, 0x4?, 0x1a28b66?})
May 22 15:55:01 C20240207094726 caddy[737]:         github.com/caddyserver/caddy/v2@v2.8.0-rc.1.0.20240521224141-61917c344342/cmd/cobra.go:137 +0x2f
May 22 15:55:01 C20240207094726 caddy[737]: github.com/spf13/cobra.(*Command).execute(0xc00001c608, {0xc0000b7f50, 0x3, 0x3})
May 22 15:55:01 C20240207094726 caddy[737]:         github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
May 22 15:55:01 C20240207094726 caddy[737]: github.com/spf13/cobra.(*Command).ExecuteC(0x2cb3b00)
May 22 15:55:01 C20240207094726 caddy[737]:         github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
May 22 15:55:01 C20240207094726 caddy[737]: github.com/spf13/cobra.(*Command).Execute(...)
May 22 15:55:01 C20240207094726 caddy[737]:         github.com/spf13/cobra@v1.8.0/command.go:1039
May 22 15:55:01 C20240207094726 caddy[737]: github.com/caddyserver/caddy/v2/cmd.Main()
May 22 15:55:01 C20240207094726 caddy[737]:         github.com/caddyserver/caddy/v2@v2.8.0-rc.1.0.20240521224141-61917c344342/cmd/main.go:75 +0x1d8
May 22 15:55:01 C20240207094726 caddy[737]: main.main()
May 22 15:55:01 C20240207094726 caddy[737]:         caddy/main.go:21 +0xf
May 22 15:55:01 C20240207094726 systemd[1]: caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 22 15:55:01 C20240207094726 systemd[1]: caddy.service: Failed with result 'exit-code'.

**Comment by imgk** [comment]
```
env CGO_ENABLED=1 XCADDY_SKIP_BUILD=0 XCADDY_SKIP_CLEANUP=0 XCADDY_GO_BUILD_FLAGS="-trimpath -ldflags '-s -w' -tags 'malloc_cgo' -v" GOPRIVATE=".github.com" \
                            /home/admin/go/bin/xcaddy build master \
                            --output /home/admin/caddy
```

```
./caddy validate --config ./caddy.json
2024/05/22 23:25:35.258	INFO	using config from file	{"file": "./caddy.json"}
2024/05/22 23:25:35.260	INFO	http.auto_https	enabling automatic HTTP->HTTPS redirects	{"server_name": "*.example.com"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xae6052]

goroutine 1 [running]:
github.com/caddyserver/caddy/v2.Context.AppIfConfigured({{0x0, 0x0}, 0x0, 0x0, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...)
	github.com/caddyserver/caddy/v2@v2.8.0-rc.1.0.20240521224141-61917c344342/context.go:462 +0x32
github.com/caddyserver/caddy/v2/modules/caddytls.(*TLS).Cleanup(0xc0004cdc20)
	github.com/caddyserver/caddy/v2@v2.8.0-rc.1.0.20240521224141-61917c344342/modules/caddytls/tls.go:356 +0xc5
github.com/caddyserver/caddy/v2.NewContext.func1()
	github.com/caddyserver/caddy/v2@v2.8.0-rc.1.0.20240521224141-61917c344342/context.go:73 +0x162
github.com/caddyserver/caddy/v2.run.func1()
	github.com/caddyserver/caddy/v2@v2.8.0-rc.1.0.20240521224141-61917c344342/caddy.go:427 +0x1d
github.com/caddyserver/caddy/v2.run(0xc0003ee770?, 0x0)
	github.com/caddyserver/caddy/v2@v2.8.0-rc.1.0.20240521224141-61917c344342/caddy.go:495 +0x918
github.com/caddyserver/caddy/v2.Validate(0xc000672780)
	github.com/caddyserver/caddy/v2@v2.8.0-rc.1.0.20240521224141-61917c344342/caddy.go:690 +0x5a
github.com/caddyserver/caddy/v2/cmd.cmdValidateConfig({0x0?})
	github.com/caddyserver/caddy/v2@v2.8.0-rc.1.0.20240521224141-61917c344342/cmd/commandfuncs.go:547 +0x155
github.com/caddyserver/caddy/v2/cmd.init.1.func8.WrapCommandFuncForCobra.1(0xc000624008, {0x1a5ea63?, 0x4?, 0x1a5ea37?})
	github.com/caddyserver/caddy/v2@v2.8.0-rc.1.0.20240521224141-61917c344342/cmd/cobra.go:137 +0x2f
github.com/spf13/cobra.(*Command).execute(0xc000624008, {0xc0002caf80, 0x2, 0x2})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0x2c900a0)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/caddyserver/caddy/v2/cmd.Main()
	github.com/caddyserver/caddy/v2@v2.8.0-rc.1.0.20240521224141-61917c344342/cmd/main.go:75 +0x1d8
main.main()
	caddy/main.go:11 +0xf
```

什么插件也没有也会报错

**Comment by imgk** [comment]
> caddy master fixed the problem https://github.com/caddyserver/caddy/commit/2ce5c6526938b604586c987fa3d31117721e40a6, i build caddy master with your patch, but a new issue comes:
> 
> 
> 
> 
> 
> ```
> 
> Error: loading http app module: provision http: loading listener wrapper modules: position 0: loading module 'trojan': provision caddy.listeners.trojan: listener: trojan is not configured 
> 
> ```

我早上看了下代码，应该是逻辑错了，所以那个分支删了

应该是这样子才对
if _, err := ctx.AppIfConfigured(); err != nil {
    return err
}

不过我也没测试过
