### ISSUE TITLE
Caddy v2.8.0 已发布

### ISSUE THREAD

**Issue by lxhao61** [imgk/caddy-trojan#66]
Caddy v2.8.0 今天已发布，而本插件基本上需要根据 Caddy 版本发布调整，是否加 Tags 标记对应。

**Comment by lxhao61** [comment]
> 已经有个 v2.8.0-rc.1 的 branch啊 

知道这个。我说的是做 Tags 标记保持版本对应，而不是另开一个分支对应。

**Comment by lxhao61** [comment]
> 做tags有个问题, 就是如果要更新tags里面的东西(更新go.sum/mod 修bug之类的, 新增功能之类的), 就要新建一个tag

哦，对开发没有太多深入，无法做到类似 Caddy 版本（Tags 标记）一样完全对应？

**Comment by lxhao61** [comment]
> > > 做tags有个问题, 就是如果要更新tags里面的东西(更新go.sum/mod 修bug之类的, 新增功能之类的), 就要新建一个tag
> > 
> > 
> > 哦，对开发没有太多深入，无法做到类似 Caddy 版本（Tags 标记）一样完全对应？
> 
> 可以的, 比如 tag v2.7.6_1 , 假设今后对这个 2.7.6 增加什么新功能修bug, 但保持对 caddy 2.7.6 做兼容, 那么就新建 tag v2.7.6_2 ...

tag 仅针对发布的正式版本，增加什么新功能或修 BUG 对 master 这样不行吗？

**Comment by imgk** [comment]
也不用那么麻烦吧，只保持对最新版本的兼容就可以了

**Comment by lxhao61** [comment]
> 也不用那么麻烦吧，只保持对最新版本的兼容就可以了

就标记而已，这样可以保证编译 Caddy 任一正式版本不会遇到错误。
