### ISSUE TITLE
可以添加详细一点的说明文档吗？

### ISSUE THREAD

**Issue by q1uxu** [imgk/caddy-trojan#67]
这个模块给caddy添加了一些细的配置，但是只给了示例，没法从示例中了解这些配置代表什么意思。可以完善一下说明文档吗？

**Comment by imgk** [comment]
其实不用在意那些没注释的配置，因为有些配置是配合我自己写的客户端才能用的，还有些是曾经想做的没有什么用的小功能，现在都不搞了，也懒得清理这些东西，忽略就好了
